// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IMainFields {
  /** Title */
  title: Document;

  /** Subtitle */
  subtitle: string;

  /** Logo */
  logo: Asset;

  /** About Us Title */
  aboutUsTitle: string;

  /** About Us Content */
  aboutUsContent: Document;

  /** About Us Content 2 */
  aboutUsContent2: Document;

  /** Activity Title */
  activityTitle: string;

  /** Activity Subtitle */
  activitySubtitle: string;

  /** Activity List */
  activityList: Asset[];

  /** Cooperation Title */
  cooperationTitle: string;

  /** Cooperation Content */
  cooperationContent: Document;

  /** Cooperation Partners Title */
  cooperationPartnersTitle: string;

  /** Cooperation Partners List */
  cooperationPartnersList: string[];

  /** Financing Title */
  financingTitle: string;

  /** Financing Content */
  financingContent: Document;

  /** Financing Content 2 */
  financingContent2: Document;

  /** Team Title */
  teamTitle: string;

  /** Team Background */
  teamBackground: Asset;

  /** Team Photos */
  teamPhotos: Asset[];

  /** Contacts Title */
  contactsTitle: string;

  /** Contacts Content */
  contactsContent: Document;
}

export interface IMain extends Entry<IMainFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "main";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "main";

export type LOCALE_CODE = "en-US" | "uk-UA";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "uk-UA";
